### ISSUE TITLE
ObjectMapper 대신 MapStruct를 사용해보는 건 어떨까요?

### ISSUE THREAD

**Issue by inspirit941** [witherview/witherview_backend#2]
수많은 채팅을 convert해야 할 수 있는데, 퍼포먼스가 가장 유려한 MapStruct로 mapper를 변경해보는 건 어떻게 생각하시나요?

https://better-dev.netlify.app/java/2020/10/26/compare_objectmapper/

**Comment by MoonYeeun** [comment]
오 대박...좋아요...또 새로운 정보 알아갑니다
ModelMapper 성능이 생각보다 안좋았군요..
이번주는 거의 프로젝트 개편작업?을 대대적으로 진행해야겠어요

**Comment by inspirit941** [comment]
https://stackoverflow.com/questions/63600368/difference-between-jackson-objectmapper-to-others
